
2023-06-02 10:32:45,483	INFO worker.py:1625 -- Started a local Ray instance.
[36m(RolloutWorker pid=38708)[39m RESETTING ENVIRONMENT!!!!!!!!!!!!!
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:32:56,941	WARNING env.py:155 -- Your env doesn't have a .spec.max_episode_steps attribute. Your horizon will default to infinity, and your environment will not be reset.
[36m(RolloutWorker pid=38708)[39m starting game.
[36m(RolloutWorker pid=38708)[39m RESETTING ENVIRONMENT!!!!!!!!!!!!!
[36m(RolloutWorker pid=38708)[39m starting game.
[36m(RolloutWorker pid=38708)[39m RESETTING ENVIRONMENT!!!!!!!!!!!!!
[36m(RolloutWorker pid=38708)[39m starting game.
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:36.614 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:36.614 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:36.614 | INFO     | sc2.controller:create_game:38 - Map:     TestMap1
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:36.614 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:36.621 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:41.242 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:41.242 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot ArmyBot(Terran)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:43.991 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:43.991 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:43.991 | INFO     | sc2.controller:create_game:38 - Map:     TestMap1
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:43.991 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:43.991 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:48.024 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:48.024 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot ArmyBot(Terran)
2023-06-02 10:33:48,498	INFO trainable.py:172 -- Trainable.setup took 67.102 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2023-06-02 10:33:48,499	WARNING util.py:67 -- Install gputil for GPU system monitoring.
[36m(RolloutWorker pid=38708)[39m armybot at... 0
[36m(RolloutWorker pid=38708)[39m RESETTING ENVIRONMENT!!!!!!!!!!!!!
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:52.096 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:52.097 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:52.097 | INFO     | sc2.controller:create_game:38 - Map:     TestMap1
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:52.097 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:52.098 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=38708)[39m starting game.
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:56.160 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:33:56.160 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot ArmyBot(Terran)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:34:15.305 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:34:15.305 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:34:15.305 | INFO     | sc2.controller:create_game:38 - Map:     TestMap1
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:34:15.305 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:34:15.306 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:34:19.299 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
[36m(RolloutWorker pid=38708)[39m 2023-06-02 10:34:19.299 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot ArmyBot(Terran)
[36m(RolloutWorker pid=38708)[39m armybot at... 0
[36m(RolloutWorker pid=38708)[39m armybot at... 10
[36m(RolloutWorker pid=38708)[39m armybot at... 20
[36m(RolloutWorker pid=38708)[39m armybot at... 30
[36m(RolloutWorker pid=38708)[39m armybot at... 40
[36m(RolloutWorker pid=38708)[39m armybot at... 50
[36m(RolloutWorker pid=38708)[39m armybot at... 60
[36m(RolloutWorker pid=38708)[39m armybot at... 70
[36m(RolloutWorker pid=38708)[39m armybot at... 80
2023-06-02 10:34:27,801	ERROR actor_manager.py:507 -- Ray error, taking actor 1 out of service. [36mray::RolloutWorker.apply()[39m (pid=38708, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001E198679FC0>)
  File "python\ray\_raylet.pyx", line 877, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 881, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\function_manager.py", line 670, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 185, in apply
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 379, in step
    self._base_env.send_actions(actions_to_send)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\env\vector_env.py", line 464, in send_actions
    ) = self.vector_env.vector_step(action_vector)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\env\vector_env.py", line 360, in vector_step
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\env\vector_env.py", line 353, in vector_step
    results = self.envs[i].step(actions[i])
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 114, in step
    self.close()
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 130, in close
    self.pcom._stop()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1047, in _stop
    assert not lock.locked()
AssertionError
Traceback (most recent call last):
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 195, in <module>
    train_ppo()
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 167, in train_ppo
    result = algo.train()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 381, in train
    result = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 792, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 2811, in _run_one_training_iteration
    results = self.training_step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\ppo\ppo.py", line 403, in training_step
    train_batch = synchronous_parallel_sample(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 722, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 75, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(AssertionError): [36mray::RolloutWorker.apply()[39m (pid=38708, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001E198679FC0>)
  File "python\ray\_raylet.pyx", line 877, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 881, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\function_manager.py", line 670, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 185, in apply
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 379, in step
    self._base_env.send_actions(actions_to_send)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\env\vector_env.py", line 464, in send_actions
    ) = self.vector_env.vector_step(action_vector)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\env\vector_env.py", line 360, in vector_step
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\env\vector_env.py", line 353, in vector_step
    results = self.envs[i].step(actions[i])
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 114, in step
    self.close()
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 130, in close
    self.pcom._stop()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1047, in _stop
    assert not lock.locked()
AssertionError
Traceback (most recent call last):
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 195, in <module>
    train_ppo()
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 167, in train_ppo
    result = algo.train()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 381, in train
    result = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 792, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 2811, in _run_one_training_iteration
    results = self.training_step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\ppo\ppo.py", line 403, in training_step
    train_batch = synchronous_parallel_sample(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 722, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 75, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(AssertionError): [36mray::RolloutWorker.apply()[39m (pid=38708, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001E198679FC0>)
  File "python\ray\_raylet.pyx", line 877, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 881, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\function_manager.py", line 670, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 185, in apply
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 379, in step
    self._base_env.send_actions(actions_to_send)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\env\vector_env.py", line 464, in send_actions
    ) = self.vector_env.vector_step(action_vector)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\env\vector_env.py", line 360, in vector_step
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\env\vector_env.py", line 353, in vector_step
    results = self.envs[i].step(actions[i])
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 114, in step
    self.close()
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 130, in close
    self.pcom._stop()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1047, in _stop
    assert not lock.locked()
AssertionError
[36m(RolloutWorker pid=38708)[39m armybot at... 90
[36m(RolloutWorker pid=38708)[39m armybot at... 100