
[36m(RolloutWorker pid=8804)[39m !RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=8804)[39m starting game.
[36m(RolloutWorker pid=8804)[39m 2023-06-08 12:08:29.949 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=8804)[39m 2023-06-08 12:08:29.949 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=8804)[39m 2023-06-08 12:08:29.949 | INFO     | sc2.controller:create_game:38 - Map:     TrainingMapResource
[36m(RolloutWorker pid=8804)[39m 2023-06-08 12:08:29.949 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=8804)[39m 2023-06-08 12:08:29.949 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=8804)[39m 2023-06-08 12:08:34.479 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
[36m(RolloutWorker pid=8804)[39m 2023-06-08 12:08:34.479 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot ArmyBot(Terran)
[36m(RolloutWorker pid=8804)[39m armybot at... 0
[36m(RolloutWorker pid=8804)[39m armybot at... 100
[36m(RolloutWorker pid=8804)[39m armybot at... 200
[36m(RolloutWorker pid=8804)[39m armybot at... 300
[36m(RolloutWorker pid=8804)[39m armybot at... 400
[36m(RolloutWorker pid=8804)[39m armybot at... 500
[36m(RolloutWorker pid=8804)[39m armybot at... 600
[36m(RolloutWorker pid=8804)[39m armybot at... 700
[36m(RolloutWorker pid=8804)[39m armybot at... 800
[36m(RolloutWorker pid=8804)[39m armybot at... 900
[36m(RolloutWorker pid=8804)[39m armybot at... 1000
[36m(RolloutWorker pid=8804)[39m armybot at... 1100
[36m(RolloutWorker pid=8804)[39m armybot at... 1200
[36m(RolloutWorker pid=8804)[39m armybot at... 1300
[36m(RolloutWorker pid=8804)[39m armybot at... 1400
[36m(RolloutWorker pid=8804)[39m armybot at... 1500
[36m(RolloutWorker pid=8804)[39m armybot at... 1600
[36m(RolloutWorker pid=8804)[39m 2023-06-08 12:08:41.217 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.ended (was Status.in_game)
[36m(RolloutWorker pid=8804)[39m Game over!
[36m(RolloutWorker pid=8804)[39m 2023-06-08 12:08:41.217 | INFO     | sc2.main:_play_game:228 - Result for player 1 - Bot ArmyBot(Terran): Victory
2023-06-08 12:08:41,386	ERROR actor_manager.py:507 -- Ray error, taking actor 1 out of service. [36mray::RolloutWorker.apply()[39m (pid=8804, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001F0A0F79FC0>)
  File "python\ray\_raylet.pyx", line 877, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 881, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\function_manager.py", line 670, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 185, in apply
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 349, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 667, in _process_observations
    self._handle_done_episode(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 820, in _handle_done_episode
    self.end_episode(env_id, episode_or_exception)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 911, in end_episode
    self._callbacks.on_episode_end(
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 119, in on_episode_end
    wandb.log({"Episode Reward": episode_reward})
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.Error: You must call wandb.init() before wandb.log()
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m [36mray::RolloutWorker.apply()[39m (pid=8804, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001F0A0F79FC0>)
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "python\ray\_raylet.pyx", line 877, in ray._raylet.execute_task
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "python\ray\_raylet.pyx", line 881, in ray._raylet.execute_task
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "python\ray\_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\function_manager.py", line 670, in actor_method_executor
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     return method(__ray_actor, *args, **kwargs)
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     return method(self, *_args, **_kwargs)
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 185, in apply
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     raise e
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     return func(self, *args, **kwargs)
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     lambda w: w.sample(), local_worker=False, healthy_only=True
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     return method(self, *_args, **_kwargs)
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     batches = [self.input_reader.next()]
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     batches = [self.get_data()]
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     item = next(self._env_runner)
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     outputs = self.step()
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 349, in step
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     active_envs, to_eval, outputs = self._process_observations(
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 667, in _process_observations
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     self._handle_done_episode(
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 820, in _handle_done_episode
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     self.end_episode(env_id, episode_or_exception)
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 911, in end_episode
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     self._callbacks.on_episode_end(
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 119, in on_episode_end
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     wandb.log({"Episode Reward": episode_reward})
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m     raise wandb.Error(f"You must call wandb.init() before {name}()")
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m wandb.errors.Error: You must call wandb.init() before wandb.log()
Traceback (most recent call last):
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 148, in <module>
    train_ppo()
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 138, in train_ppo
    result = algo.train()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 381, in train
    result = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 792, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 2811, in _run_one_training_iteration
    results = self.training_step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\ppo\ppo.py", line 403, in training_step
    train_batch = synchronous_parallel_sample(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 722, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 75, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(Error): [36mray::RolloutWorker.apply()[39m (pid=8804, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001F0A0F79FC0>)
  File "python\ray\_raylet.pyx", line 877, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 881, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\function_manager.py", line 670, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 185, in apply
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 349, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 667, in _process_observations
    self._handle_done_episode(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 820, in _handle_done_episode
    self.end_episode(env_id, episode_or_exception)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 911, in end_episode
    self._callbacks.on_episode_end(
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 119, in on_episode_end
    wandb.log({"Episode Reward": episode_reward})
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.Error: You must call wandb.init() before wandb.log()
Traceback (most recent call last):
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 148, in <module>
    train_ppo()
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 138, in train_ppo
    result = algo.train()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 381, in train
    result = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 792, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 2811, in _run_one_training_iteration
    results = self.training_step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\ppo\ppo.py", line 403, in training_step
    train_batch = synchronous_parallel_sample(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 722, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 75, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(Error): [36mray::RolloutWorker.apply()[39m (pid=8804, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001F0A0F79FC0>)
  File "python\ray\_raylet.pyx", line 877, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 881, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\function_manager.py", line 670, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 185, in apply
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 349, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 667, in _process_observations
    self._handle_done_episode(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 820, in _handle_done_episode
    self.end_episode(env_id, episode_or_exception)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 911, in end_episode
    self._callbacks.on_episode_end(
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 119, in on_episode_end
    wandb.log({"Episode Reward": episode_reward})
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.Error: You must call wandb.init() before wandb.log()