
2023-06-06 18:07:58,825	INFO worker.py:1625 -- Started a local Ray instance.
[36m(RolloutWorker pid=31564)[39m !RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:09,985	WARNING env.py:155 -- Your env doesn't have a .spec.max_episode_steps attribute. Your horizon will default to infinity, and your environment will not be reset.
[36m(RolloutWorker pid=31564)[39m starting game.
[36m(RolloutWorker pid=31564)[39m !RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=31564)[39m starting game.!RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=31564)
[36m(RolloutWorker pid=31564)[39m starting game.
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:22.155 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:22.155 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:22.155 | INFO     | sc2.controller:create_game:38 - Map:     TrainingMapResource
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:22.155 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:22.156 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:26.014 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:26.014 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:26.014 | INFO     | sc2.controller:create_game:38 - Map:     TrainingMapResource
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:26.014 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:26.015 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:26.392 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:26.392 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot ArmyBot(Terran)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:30.298 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:30.299 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot ArmyBot(Terran)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:31.203 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:31.203 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:31.203 | INFO     | sc2.controller:create_game:38 - Map:     TrainingMapResource
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:31.203 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:31.204 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=31564)[39m C:\Users\Emil WC\Bachelor\RL-SC2-bot\ArmyBotResource.py:86: RuntimeWarning: coroutine 'BotAI.distribute_workers' was never awaited
[36m(RolloutWorker pid=31564)[39m   self.distribute_workers()
[36m(RolloutWorker pid=31564)[39m RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2023-06-06 18:08:35,602	INFO trainable.py:172 -- Trainable.setup took 38.864 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2023-06-06 18:08:35,603	WARNING util.py:67 -- Install gputil for GPU system monitoring.
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:35.283 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:35.283 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot ArmyBot(Terran)
[36m(RolloutWorker pid=31564)[39m 50
[36m(RolloutWorker pid=31564)[39m armybot at... 0
[36m(RolloutWorker pid=31564)[39m !RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=31564)[39m starting game.
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:52.162 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:52.162 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:52.163 | INFO     | sc2.controller:create_game:38 - Map:     TrainingMapResource
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:52.163 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:52.163 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=31564)[39m C:\Users\Emil WC\Bachelor\RL-SC2-bot\ArmyBotResource.py:86: RuntimeWarning: coroutine 'BotAI.distribute_workers' was never awaited
[36m(RolloutWorker pid=31564)[39m   self.distribute_workers()
[36m(RolloutWorker pid=31564)[39m RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2023-06-06 18:08:56,938	ERROR actor_manager.py:507 -- Ray error, taking actor 1 out of service. [36mray::RolloutWorker.apply()[39m (pid=31564, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001CD140E5F90>)
  File "python\ray\_raylet.pyx", line 877, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 881, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\function_manager.py", line 670, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 185, in apply
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 349, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 616, in _process_observations
    processed = policy.agent_connectors(acd_list)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\agent\pipeline.py", line 41, in __call__
    ret = c(ret)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\connector.py", line 254, in __call__
    return [self.transform(d) for d in acd_list]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\connector.py", line 254, in <listcomp>
    return [self.transform(d) for d in acd_list]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\agent\obs_preproc.py", line 58, in transform
    d[SampleBatch.NEXT_OBS] = self._preprocessor.transform(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\models\preprocessors.py", line 191, in transform
    return gym.spaces.utils.flatten(self._obs_space, observation).astype(np.float32)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\gymnasium\spaces\utils.py", line 157, in _flatten_multidiscrete
    onehot[offsets[:-1] + x.flatten()] = 1
IndexError: index 65526 is out of bounds for axis 0 with size 1045
Traceback (most recent call last):
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 157, in <module>
    train_ppo()
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 135, in train_ppo
    result = algo.train()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 381, in train
    result = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 792, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 2811, in _run_one_training_iteration
    results = self.training_step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\ppo\ppo.py", line 403, in training_step
    train_batch = synchronous_parallel_sample(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 722, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 75, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(IndexError): [36mray::RolloutWorker.apply()[39m (pid=31564, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001CD140E5F90>)
  File "python\ray\_raylet.pyx", line 877, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 881, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\function_manager.py", line 670, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 185, in apply
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 349, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 616, in _process_observations
    processed = policy.agent_connectors(acd_list)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\agent\pipeline.py", line 41, in __call__
    ret = c(ret)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\connector.py", line 254, in __call__
    return [self.transform(d) for d in acd_list]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\connector.py", line 254, in <listcomp>
    return [self.transform(d) for d in acd_list]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\agent\obs_preproc.py", line 58, in transform
    d[SampleBatch.NEXT_OBS] = self._preprocessor.transform(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\models\preprocessors.py", line 191, in transform
    return gym.spaces.utils.flatten(self._obs_space, observation).astype(np.float32)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\gymnasium\spaces\utils.py", line 157, in _flatten_multidiscrete
    onehot[offsets[:-1] + x.flatten()] = 1
IndexError: index 65526 is out of bounds for axis 0 with size 1045
Traceback (most recent call last):
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 157, in <module>
    train_ppo()
  File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 135, in train_ppo
    result = algo.train()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\tune\trainable\trainable.py", line 381, in train
    result = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 792, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 2811, in _run_one_training_iteration
    results = self.training_step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\ppo\ppo.py", line 403, in training_step
    train_batch = synchronous_parallel_sample(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 85, in synchronous_parallel_sample
    sample_batches = worker_set.foreach_worker(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 722, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 75, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(IndexError): [36mray::RolloutWorker.apply()[39m (pid=31564, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001CD140E5F90>)
  File "python\ray\_raylet.pyx", line 877, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 881, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 821, in ray._raylet.execute_task.function_executor
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\_private\function_manager.py", line 670, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 185, in apply
    raise e
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\utils\actor_manager.py", line 176, in apply
    return func(self, *args, **kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 86, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\util\tracing\tracing_helper.py", line 460, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 915, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\sampler.py", line 277, in get_data
    item = next(self._env_runner)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 323, in run
    outputs = self.step()
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 349, in step
    active_envs, to_eval, outputs = self._process_observations(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 616, in _process_observations
    processed = policy.agent_connectors(acd_list)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\agent\pipeline.py", line 41, in __call__
    ret = c(ret)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\connector.py", line 254, in __call__
    return [self.transform(d) for d in acd_list]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\connector.py", line 254, in <listcomp>
    return [self.transform(d) for d in acd_list]
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\connectors\agent\obs_preproc.py", line 58, in transform
    d[SampleBatch.NEXT_OBS] = self._preprocessor.transform(
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\models\preprocessors.py", line 191, in transform
    return gym.spaces.utils.flatten(self._obs_space, observation).astype(np.float32)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\gymnasium\spaces\utils.py", line 157, in _flatten_multidiscrete
    onehot[offsets[:-1] + x.flatten()] = 1
IndexError: index 65526 is out of bounds for axis 0 with size 1045
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:56.432 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
[36m(RolloutWorker pid=31564)[39m 2023-06-06 18:08:56.433 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot ArmyBot(Terran)
[36m(RolloutWorker pid=31564)[39m 50
[36m(RolloutWorker pid=31564)[39m armybot at... 0
[36m(RolloutWorker pid=31564)[39m 50
[36m(RolloutWorker pid=31564)[39m 50
[36m(RolloutWorker pid=31564)[39m 50
[36m(RolloutWorker pid=31564)[39m 50