
2023-06-06 15:57:33,774	INFO worker.py:1625 -- Started a local Ray instance.
[36m(RolloutWorker pid=31112)[39m !RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=31112)[39m starting game.
[36m(RolloutWorker pid=31112)[39m !RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:57:45,869	WARNING env.py:155 -- Your env doesn't have a .spec.max_episode_steps attribute. Your horizon will default to infinity, and your environment will not be reset.
[36m(RolloutWorker pid=31112)[39m starting game.!RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m starting game.
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:57:58.226 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:57:58.226 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:57:58.226 | INFO     | sc2.controller:create_game:38 - Map:     ArmyBotTrainingMap
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:57:58.226 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:57:58.227 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:03.559 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:03.559 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot ArmyBot(Terran)
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:03.823 | ERROR    | sc2.main:initialize_first_step:140 - Caught unknown exception in AI on_start: y is 32, self.height is 32
[36m(RolloutWorker pid=31112)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
[36m(RolloutWorker pid=31112)[39m     self._bootstrap_inner()
[36m(RolloutWorker pid=31112)[39m     â”‚    â”” <function Thread._bootstrap_inner at 0x00000200F70C0820>
[36m(RolloutWorker pid=31112)[39m     â”” <AST(Thread-2, started 28208)>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
[36m(RolloutWorker pid=31112)[39m     self.run()
[36m(RolloutWorker pid=31112)[39m     â”‚    â”” <function AST.run at 0x00000200F5119510>
[36m(RolloutWorker pid=31112)[39m     â”” <AST(Thread-2, started 28208)>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 31, in run
[36m(RolloutWorker pid=31112)[39m     result = run_game(  # run_game is a function that runs the game.
[36m(RolloutWorker pid=31112)[39m              â”” <function run_game at 0x00000200F4F5E4D0>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 496, in run_game
[36m(RolloutWorker pid=31112)[39m     result: Result = asyncio.run(_host_game(map_settings, players, **kwargs))
[36m(RolloutWorker pid=31112)[39m                      â”‚       â”‚   â”‚          â”‚             â”‚          â”” {'realtime': False}
[36m(RolloutWorker pid=31112)[39m                      â”‚       â”‚   â”‚          â”‚             â”” [<sc2.player.Bot object at 0x00000200F50F5630>, <sc2.player.Computer object at 0x00000200F50F5600>]
[36m(RolloutWorker pid=31112)[39m                      â”‚       â”‚   â”‚          â”” Map(C:\Program Files (x86)\StarCraft II\maps\ArmyBotTrainingMap.SC2Map)
[36m(RolloutWorker pid=31112)[39m                      â”‚       â”‚   â”” <function _host_game at 0x00000200F4F5E0E0>
[36m(RolloutWorker pid=31112)[39m                      â”‚       â”” <function run at 0x00000200F714CC10>
[36m(RolloutWorker pid=31112)[39m                      â”” <module 'asyncio' from 'C:\\Users\\Emil WC\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\__init__.py'>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
[36m(RolloutWorker pid=31112)[39m     return loop.run_until_complete(main)
[36m(RolloutWorker pid=31112)[39m            â”‚    â”‚                  â”” <coroutine object _host_game at 0x00000200F5108AC0>
[36m(RolloutWorker pid=31112)[39m            â”‚    â”” <function BaseEventLoop.run_until_complete at 0x00000200F8B24D30>
[36m(RolloutWorker pid=31112)[39m            â”” <ProactorEventLoop running=True closed=False debug=False>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
[36m(RolloutWorker pid=31112)[39m     self.run_forever()
[36m(RolloutWorker pid=31112)[39m     â”‚    â”” <function ProactorEventLoop.run_forever at 0x00000200F8BED510>
[36m(RolloutWorker pid=31112)[39m     â”” <ProactorEventLoop running=True closed=False debug=False>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
[36m(RolloutWorker pid=31112)[39m     super().run_forever()
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
[36m(RolloutWorker pid=31112)[39m     self._run_once()
[36m(RolloutWorker pid=31112)[39m     â”‚    â”” <function BaseEventLoop._run_once at 0x00000200F8B267A0>
[36m(RolloutWorker pid=31112)[39m     â”” <ProactorEventLoop running=True closed=False debug=False>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
[36m(RolloutWorker pid=31112)[39m     handle._run()
[36m(RolloutWorker pid=31112)[39m     â”‚      â”” <function Handle._run at 0x00000200F8A85990>
[36m(RolloutWorker pid=31112)[39m     â”” <Handle Task.task_wakeup(<Future finished result=None>)>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
[36m(RolloutWorker pid=31112)[39m     self._context.run(self._callback, *self._args)
[36m(RolloutWorker pid=31112)[39m     â”‚    â”‚            â”‚    â”‚           â”‚    â”” <member '_args' of 'Handle' objects>
[36m(RolloutWorker pid=31112)[39m     â”‚    â”‚            â”‚    â”‚           â”” <Handle Task.task_wakeup(<Future finished result=None>)>
[36m(RolloutWorker pid=31112)[39m     â”‚    â”‚            â”‚    â”” <member '_callback' of 'Handle' objects>
[36m(RolloutWorker pid=31112)[39m     â”‚    â”‚            â”” <Handle Task.task_wakeup(<Future finished result=None>)>
[36m(RolloutWorker pid=31112)[39m     â”‚    â”” <member '_context' of 'Handle' objects>
[36m(RolloutWorker pid=31112)[39m     â”” <Handle Task.task_wakeup(<Future finished result=None>)>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 369, in _host_game
[36m(RolloutWorker pid=31112)[39m     result = await _play_game(players[0], client, realtime, portconfig, game_time_limit, rgb_render_config)
[36m(RolloutWorker pid=31112)[39m                    â”‚          â”‚           â”‚       â”‚         â”‚           â”‚                â”” None
[36m(RolloutWorker pid=31112)[39m                    â”‚          â”‚           â”‚       â”‚         â”‚           â”” None
[36m(RolloutWorker pid=31112)[39m                    â”‚          â”‚           â”‚       â”‚         â”” None
[36m(RolloutWorker pid=31112)[39m                    â”‚          â”‚           â”‚       â”” False
[36m(RolloutWorker pid=31112)[39m                    â”‚          â”‚           â”” <sc2.client.Client object at 0x00000200F513C520>
[36m(RolloutWorker pid=31112)[39m                    â”‚          â”” [<sc2.player.Bot object at 0x00000200F50F5630>, <sc2.player.Computer object at 0x00000200F50F5600>]
[36m(RolloutWorker pid=31112)[39m                    â”” <function _play_game at 0x00000200F4F5DF30>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 226, in _play_game
[36m(RolloutWorker pid=31112)[39m     result = await _play_game_ai(client, player_id, player.ai, realtime, game_time_limit)
[36m(RolloutWorker pid=31112)[39m                    â”‚             â”‚       â”‚          â”‚      â”‚   â”‚         â”” None
[36m(RolloutWorker pid=31112)[39m                    â”‚             â”‚       â”‚          â”‚      â”‚   â”” False
[36m(RolloutWorker pid=31112)[39m                    â”‚             â”‚       â”‚          â”‚      â”” <ArmyBotMarine.ArmyBot object at 0x00000200F50F48B0>
[36m(RolloutWorker pid=31112)[39m                    â”‚             â”‚       â”‚          â”” <sc2.player.Bot object at 0x00000200F50F5630>
[36m(RolloutWorker pid=31112)[39m                    â”‚             â”‚       â”” 1
[36m(RolloutWorker pid=31112)[39m                    â”‚             â”” <sc2.client.Client object at 0x00000200F513C520>
[36m(RolloutWorker pid=31112)[39m                    â”” <function _play_game_ai at 0x00000200F4F5DC60>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 145, in _play_game_ai
[36m(RolloutWorker pid=31112)[39m     result = await initialize_first_step()
[36m(RolloutWorker pid=31112)[39m                    â”” <function _play_game_ai.<locals>.initialize_first_step at 0x00000200F511AB00>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m > File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 135, in initialize_first_step
[36m(RolloutWorker pid=31112)[39m     ai._prepare_first_step()
[36m(RolloutWorker pid=31112)[39m     â”‚  â”” <function BotAIInternal._prepare_first_step at 0x00000200F4BFEE60>
[36m(RolloutWorker pid=31112)[39m     â”” <ArmyBotMarine.ArmyBot object at 0x00000200F50F48B0>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\bot_ai_internal.py", line 472, in _prepare_first_step
[36m(RolloutWorker pid=31112)[39m     self._find_expansion_locations()
[36m(RolloutWorker pid=31112)[39m     â”‚    â”” <function BotAIInternal._find_expansion_locations at 0x00000200F4BFE950>
[36m(RolloutWorker pid=31112)[39m     â”” <ArmyBotMarine.ArmyBot object at 0x00000200F50F48B0>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\bot_ai_internal.py", line 232, in _find_expansion_locations
[36m(RolloutWorker pid=31112)[39m     result: Point2 = min(
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\bot_ai_internal.py", line 224, in <genexpr>
[36m(RolloutWorker pid=31112)[39m     if self.game_info.placement_grid[point.rounded] == 1
[36m(RolloutWorker pid=31112)[39m        â”‚    â”‚         â”‚              â”‚     â”” <property object at 0x00000200F4B9A930>
[36m(RolloutWorker pid=31112)[39m        â”‚    â”‚         â”‚              â”” (15.5, 32.5)
[36m(RolloutWorker pid=31112)[39m        â”‚    â”‚         â”” <sc2.pixel_map.PixelMap object at 0x00000200F5205630>
[36m(RolloutWorker pid=31112)[39m        â”‚    â”” <sc2.game_info.GameInfo object at 0x00000200F51C3D60>
[36m(RolloutWorker pid=31112)[39m        â”” <ArmyBotMarine.ArmyBot object at 0x00000200F50F48B0>
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\pixel_map.py", line 47, in __getitem__
[36m(RolloutWorker pid=31112)[39m     assert 0 <= pos[1] < self.height, f"y is {pos[1]}, self.height is {self.height}"
[36m(RolloutWorker pid=31112)[39m                 â”‚        â”‚    â”” <property object at 0x00000200F4BAE430>
[36m(RolloutWorker pid=31112)[39m                 â”‚        â”” <sc2.pixel_map.PixelMap object at 0x00000200F5205630>
[36m(RolloutWorker pid=31112)[39m                 â”” (15, 32)
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m AssertionError: y is 32, self.height is 32
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:03.845 | ERROR    | sc2.main:initialize_first_step:141 - Resigning due to previous error
[36m(RolloutWorker pid=31112)[39m Game over!
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:03.845 | INFO     | sc2.main:_play_game:228 - Result for player 1 - Bot ArmyBot(Terran): Defeat
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:04.790 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was Status.in_game)
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:04.791 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.quit (was Status.launched)
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:04.791 | INFO     | sc2.sc2process:_close_connection:231 - Closing connection at 51574...
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:04.792 | INFO     | sc2.sc2process:kill_all:33 - kill_switch: Process cleanup for 3 processes
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:05.032 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:05.032 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:05.032 | INFO     | sc2.controller:create_game:38 - Map:     ArmyBotTrainingMap
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:05.033 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:05.034 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:05.333 | ERROR    | sc2.protocol:__request:50 - Cannot receive: Connection already closed.
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:05.333 | INFO     | sc2.sc2process:_close_connection:231 - Closing connection at 51600...
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:05.333 | INFO     | sc2.sc2process:kill_all:33 - kill_switch: Process cleanup for 3 processes
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:06.371 | INFO     | sc2.sc2process:_close_connection:231 - Closing connection at None...
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:06.371 | INFO     | sc2.sc2process:_clean:242 - Cleaning up...
[36m(RolloutWorker pid=31112)[39m 2023-06-06 15:58:06.371 | INFO     | sc2.sc2process:_clean:274 - Cleanup complete
[36m(RolloutWorker pid=31112)[39m Exception in thread Thread-3:
[36m(RolloutWorker pid=31112)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\protocol.py", line 45, in __request
[36m(RolloutWorker pid=31112)[39m     response_bytes = await self._ws.receive_bytes()
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_ws.py", line 281, in receive_bytes
[36m(RolloutWorker pid=31112)[39m     raise TypeError(f"Received message {msg.type}:{msg.data!r} is not bytes")
[36m(RolloutWorker pid=31112)[39m TypeError: Received message 257:None is not bytes
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m The above exception was the direct cause of the following exception:
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
[36m(RolloutWorker pid=31112)[39m     self.run()
[36m(RolloutWorker pid=31112)[39m   File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 31, in run
[36m(RolloutWorker pid=31112)[39m     result = run_game(  # run_game is a function that runs the game.
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 496, in run_game
[36m(RolloutWorker pid=31112)[39m     result: Result = asyncio.run(_host_game(map_settings, players, **kwargs))
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
[36m(RolloutWorker pid=31112)[39m     return loop.run_until_complete(main)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
[36m(RolloutWorker pid=31112)[39m     return future.result()
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 369, in _host_game
[36m(RolloutWorker pid=31112)[39m     result = await _play_game(players[0], client, realtime, portconfig, game_time_limit, rgb_render_config)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 218, in _play_game
[36m(RolloutWorker pid=31112)[39m     player_id = await client.join_game(
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\client.py", line 99, in join_game
[36m(RolloutWorker pid=31112)[39m     result = await self._execute(join_game=req)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\protocol.py", line 68, in _execute
[36m(RolloutWorker pid=31112)[39m     response = await self.__request(sc_pb.Request(**kwargs))
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\protocol.py", line 51, in __request
[36m(RolloutWorker pid=31112)[39m     raise ConnectionAlreadyClosed("Connection already closed.") from exc
[36m(RolloutWorker pid=31112)[39m sc2.protocol.ConnectionAlreadyClosed: Connection already closed.
[36m(RolloutWorker pid=31112)[39m Exception in thread Thread-4:
[36m(RolloutWorker pid=31112)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\yarl\_url.py", line 191, in __new__
[36m(RolloutWorker pid=31112)[39m     port = val.port
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\urllib\parse.py", line 177, in port
[36m(RolloutWorker pid=31112)[39m     raise ValueError(f"Port could not be cast to integer value as {port!r}")
[36m(RolloutWorker pid=31112)[39m ValueError: Port could not be cast to integer value as 'None'
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m The above exception was the direct cause of the following exception:
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 423, in _request
[36m(RolloutWorker pid=31112)[39m     url = self._build_url(str_or_url)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 357, in _build_url
[36m(RolloutWorker pid=31112)[39m     url = URL(str_or_url)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\yarl\_url.py", line 193, in __new__
[36m(RolloutWorker pid=31112)[39m     raise ValueError(
[36m(RolloutWorker pid=31112)[39m ValueError: Invalid URL: port can't be converted to integer
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m The above exception was the direct cause of the following exception:
[36m(RolloutWorker pid=31112)
[36m(RolloutWorker pid=31112)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
[36m(RolloutWorker pid=31112)[39m     self.run()
[36m(RolloutWorker pid=31112)[39m   File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 31, in run
[36m(RolloutWorker pid=31112)[39m     result = run_game(  # run_game is a function that runs the game.
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 496, in run_game
[36m(RolloutWorker pid=31112)[39m     result: Result = asyncio.run(_host_game(map_settings, players, **kwargs))
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
[36m(RolloutWorker pid=31112)[39m     return loop.run_until_complete(main)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
[36m(RolloutWorker pid=31112)[39m     return future.result()
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 357, in _host_game
[36m(RolloutWorker pid=31112)[39m     async with SC2Process(
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\sc2process.py", line 108, in __aenter__
[36m(RolloutWorker pid=31112)[39m     self._ws = await self._connect()
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\sc2process.py", line 215, in _connect
[36m(RolloutWorker pid=31112)[39m     ws = await self._session.ws_connect(self.ws_url, timeout=120)
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 779, in _ws_connect
[36m(RolloutWorker pid=31112)[39m     resp = await self.request(
[36m(RolloutWorker pid=31112)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 425, in _request
[36m(RolloutWorker pid=31112)[39m     raise InvalidURL(str_or_url) from e
